# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 78ac56e
_src_path: .
author_email: test@example.com
author_name: Test Author
github_username: test-user
license: MIT
max_python_version: "3.15"
min_python_version: "3.12"
project_description: ""
project_name: Test Project
project_type: Library
use_codecov: false
use_ty: true
